### ISSUE TITLE
Currency card for ether and ERC-20 tokens not showing after successful transaction

### ISSUE THREAD

**Issue by farrahfazirah** [alpha-wallet/alpha-wallet-ios#680]
Stumbled upon this bug during user testing so they're new users.

When user receives ether, they can't see the successful transaction immediately (while they're still on the app). They can see in the history of transactions that they have received the ether but they have to restart the AlphaWallet app to see the currency card appear.

Same goes for ERC-20 tokens.

**Comment by James-Sangalli** [comment]
@hboon @farrahfazirah the erc20 tokens cannot show up when the user is the reciever due to ethereum's design and the ether showing up will never be instant as querying for this lags but there might be a way we can speed it up with our own node (keeping infura as a backup).

**Comment by hboon** [comment]
@farrahfazirah but are you saying that the ether value does not get updated after a while (say a minute) until you restart the app?

**Comment by farrahfazirah** [comment]
@hboon After onboarding, there was no asset card.

When user receives ether, it is reflected on the user's transaction page that the transaction was successful. However, when user goes to check ether in their wallet, there is still no asset card but they only see a similar screen below.

![f3d33b3e-a2ed-4361-94e2-05d83e0fa2f1](https://user-images.githubusercontent.com/20555752/45024381-6e1a3280-b06b-11e8-805b-2422898bc326.jpeg)

They restarted the app and they finally had the asset card for ether with the ether they received.

**Comment by hboon** [comment]
@farrahfazirah I looked at the code and can't figure out how to reproduce it so that the ether card don't appear in the wallet tab even with a new download. If you manage to reproduce it, can you help me know? It's bad.

Otherwise, both the ether card and the My Wallet Address screen are _supposed_ to refresh periodically to pull the latest ether balance. Even they don't, it's a bug.

A tip for the users when they test: if they find a bug, go to Settings tab > Help & FAQs > Still need help? Contact Us. Email or note down the information at the bottom (iOS version, etc).

**Comment by hboon** [comment]
I figured it out! To reproduce:

1. Go to wallet tab
2. Tap on "ASSETS"
3. Refresh or wait a while for it to auto-fresh

Thanks @farrahfazirah !

Filed at #694
